name: Build & Code Quality Checks

on:
  pull_request:
    branches: [ 'develop', 'main' ]
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    name: Build & Code Quality Checks
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Set Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install node_modules
        run: |
          npm ci

      - name: Build
        run: |
          npm run build
      - name: Unit test
        run: |
          npm run test
